### ISSUE TITLE
top 10k english words that are words?

### ISSUE THREAD

**Issue by tedder** [first20hours/google-10000-english#10]
Hi, are you interested in having another permutation of the 10k list that is only valid words? [I needed that](https://github.com/stansonhealth/interview-coding-tasks/tree/master/anagrams#input), so I munged the list a little. You probably would want the whole 10k, but it's pretty close to what I ran.

This is relevant to #1.

**Comment by worldlywisdom** [comment]
Not sure what you're asking here.

**Comment by tedder** [comment]
What I'm saying is the top 10k includes strings that aren't words that would appear in a dictionary- like "rl", "gl", "dh", "x", "n", and so on. I was linking code to be helpful. Never mind, I guess.
