### ISSUE TITLE
Why are there ~1500 duplicate words here?

### ISSUE THREAD

**Issue by farzher** [first20hours/google-10000-english#6]
Shouldn't the list be deduplicated?

**Comment by kylemcdonald** [comment]
Yes, it looks like 20k has a lot of duplicates, and 10 for the `usa` file:

```
$ wc -l < 20k.txt 
   19999
$ sort 20k.txt | uniq | wc -l
   18529
$ wc -l < google-10000-english-usa.txt 
    9999
$ sort google-10000-english-usa.txt | uniq | wc -l
    9989
```

**Comment by whitten** [comment]
I don't know. Is it a case sensitivity issue?
Does sort or uniq only get one of "this" and "This" ?

**Comment by farzher** [comment]
It's not a case issue. It's exact duplicates. Check using any random dedupe tool.

![image](https://cloud.githubusercontent.com/assets/1005136/8383037/23d55112-1c05-11e5-8ee7-308662e4851f.png)

Apparently `Word` is in there 9 times

**Comment by koseki** [comment]
It seems to combine two different sources.

I'm checking the frequency rankings of [this list](http://www.freevocabulary.com/) using `20k.txt`, and the result is this.

![freq-g20k](https://cloud.githubusercontent.com/assets/11028/16906318/ccf7e1c0-4cf0-11e6-8a03-51a4b8abc6ec.png)

The original [`count_1w.txt`](http://norvig.com/ngrams/) shows the straight graph.

![freq](https://cloud.githubusercontent.com/assets/11028/16906208/703a8200-4cee-11e6-96c4-447b59fa19dd.png)

![shot 186](https://cloud.githubusercontent.com/assets/11028/16906444/db74af56-4cf2-11e6-8d89-71e1fd8ef02a.png)

**Comment by worldlywisdom** [comment]
Great catch - not sure why the the original source has duplicates. I appreciate the fix.
